Repository vkvbit/JS-repo, pull requests merged in 2022-10, with the labels that each got.

#1 Update main.js
  main.js
Labels: hacktoberfest-accepted

#2 update readme
  README.md
Labels: hacktoberfest-accepted

#3 Update README.md
  README.md
Labels: hacktoberfest-accepted

#4 Update README.md
  README.md
Labels: hacktoberfest-accepted

#5 Create Input.js
  Input.js
Labels: hacktoberfest-accepted

#7 Create input2.js
  input2.js
Labels: hacktoberfest-accepted

#8 Create input3.js
  input3.js
Labels: hacktoberfest-accepted

#10 Create temp.js
  temp.js
Labels: good first issue, hacktoberfest-accepted

#11 Create temp1.js
  temp1.js
Labels: hacktoberfest-accepted

#12 Create temp2.js
  temp2.js
Labels: hacktoberfest-accepted

#14 Create temp4.js
  temp4.js
Labels: enhancement, hacktoberfest-accepted

#15 Update main.js
  main.js
Labels: hacktoberfest-accepted

#16 Update temp.js
  temp.js
Labels: hacktoberfest-accepted

#17 Update temp4.js
  temp4.js
Labels: hacktoberfest-accepted

#18 Update input2.js
  input2.js
Labels: hacktoberfest-accepted

#19 Update input3.js
  input3.js
Labels: hacktoberfest-accepted

#20 Update main.js
  main.js
Labels: hacktoberfest-accepted

#21 Update new.js
  input2.js
  new.js
Labels: hacktoberfest-accepted

#22 Update input2.js
  input2.js
Labels: enhancement, hacktoberfest-accepted

#23 Update temp.js
  temp.js
Labels: hacktoberfest-accepted

#24 Update input2.js
  input2.js
Labels: hacktoberfest-accepted

#25 kya kahu
  temp.js
Labels: hacktoberfest-accepted

#26 Create deep.1
  deep.1
Labels: hacktoberfest-accepted

#27 Create deep.2
  deep.2
Labels: enhancement, hacktoberfest-accepted

#30 Create deep.5
  deep.5
Labels: hacktoberfest-accepted

#29 Create deep.4
  deep.4
Labels: enhancement, hacktoberfest-accepted

#31 Create manu.1
  manu.1
Labels: good first issue, hacktoberfest-accepted

#32 Create manu.2
  manu.2
Labels: hacktoberfest-accepted

#33 Create manu.3
  manu.3
Labels: hacktoberfest-accepted

#34 Create manu.4
  manu.4
Labels: hacktoberfest-accepted

#35 Create manu.5
  manu.5
Labels: hacktoberfest-accepted

#36 Create bhup.1
  bhup.1
Labels: invalid

#38 Create bhup.3
  bhup.3
Labels: hacktoberfest-accepted

#39 Create bhup.4
  bhup.4
Labels: hacktoberfest-accepted

#40 Create bhup.5
  bhup.5
Labels: hacktoberfest-accepted

#42 Create dheeraj.2
  dheeraj.2
Labels: enhancement, hacktoberfest-accepted

#43 Create dheeraj.3
  dheeraj.3
Labels: hacktoberfest-accepted

#44 Create dheeraj.4
  dheeraj.4
Labels: hacktoberfest-accepted

#45 Create dheeraj.5
  dheeraj.5
Labels: hacktoberfest-accepted
